name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: mkdir build && cd build
    - name: cmake
      run: pwd && cmake --version && cmake ..
    - name: make
      run: make -j 4
    - name: test
      run: cd test && ./gemm && ./conv2d
